### ISSUE TITLE
Major problem with site

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lantius/flashvolunteer#164]
```
Upon navigating away from the Settings page, I get the following error:

Traceback (most recent call last):
  File "/base/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 507, in 
__call__
    handler.get(*groups)
  File "/base/data/home/apps/flashvolunteer/v01-
2.335789908346230742/controllers/home.py", line 32, in get
    self.homepage(volunteer)
  File "/base/data/home/apps/flashvolunteer/v01-
2.335789908346230742/controllers/home.py", line 53, in homepage
    events = { 'Your events' : volunteer.events() }
  File "/base/data/home/apps/flashvolunteer/v01-
2.335789908346230742/models/volunteer.py", line 133, in events
    events = [ev.event for ev in self.eventvolunteers]
  File "/base/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 2759, in __get__
    raise Error('ReferenceProperty failed to be resolved')
Error: ReferenceProperty failed to be resolved

I think it had to do with deleting a few past events from the Event data store. 

```

Original issue reported on code.google.com by `jbwi...@gmail.com` on 5 Sep 2009 at 5:47

**Comment by GoogleCodeExporter** [comment]
Original comment by `tkripl...@gmail.com` on 10 Sep 2009 at 2:03
- Changed state: **Done**
