### ISSUE TITLE
Log-in attempt takes me to traceback error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lantius/flashvolunteer#23]
```
What steps will reproduce the problem?
1. Log-in on Google account via IE
2.
3.

What is the expected output? What do you see instead?
Instead of being taken to the site, I am taken to an error page (copied below)

What web browser are you using (Firefox, Safari, Internet Explorer)? IE


Please provide any additional information below.

Traceback (most recent call last):
  File "/base/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 501, in 
__call__
    handler.get(*groups)
  File "/base/data/home/apps/flashvolunteer/2.333403122888558177/controllers/home.py", 
line 30, in get
    self.homepage(volunteer)
  File "/base/data/home/apps/flashvolunteer/2.333403122888558177/controllers/home.py", 
line 52, in homepage
    if volunteer.home_neighborhood:
  File "/base/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 2644, in __get__
    raise Error('ReferenceProperty failed to be resolved')
Error: ReferenceProperty failed to be resolved
```

Original issue reported on code.google.com by `brad%fla...@gtempaccount.com` on 15 May 2009 at 1:20

**Comment by GoogleCodeExporter** [comment]
Original comment by `tkripl...@gmail.com` on 17 May 2009 at 5:16
- Changed state: **Fixed**
