### ISSUE TITLE
Get existing GUI tests working and functional

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lantius/flashvolunteer#88]
```
Currently there are 8 errors/failures that need to be fixed. We need them all 
cleared up before we can launch. Without it bug fixes will need to be 
manually regressed.
```

Original issue reported on code.google.com by `tla...@gmail.com` on 8 Jul 2009 at 8:10

**Comment by GoogleCodeExporter** [comment]
Original comment by `tla...@gmail.com` on 10 Jul 2009 at 5:59

**Comment by GoogleCodeExporter** [comment]
```
Could you post where the 8 errors/failures occur. My selenium install developed 
some
strange problems recently, the automated test of all does not work for me. But 
I can
still run individual tests, so if I knew which tests are failing, I could 
address
theses manually.
```

Original comment by `acwa...@gmail.com` on 12 Jul 2009 at 9:30

**Comment by GoogleCodeExporter** [comment]
```
from Toby's post
(http://groups.google.com/group/flashvolunteer-dev/browse_thread/thread/924d969d
5fe45c7e?hl=en)
################################################################################
ERROR: test_edit_upcoming_event
(gui_integration_tests.tests.edit_event.TestEditEvent__Owner)
????????????????????????????????????????????????????????????????????????????????

Traceback (most recent call last):
  File "gui_integration_tests/tests/edit_event.py", line 52, in
test_edit_upcoming_event
    self._click_interestcategory(name = '1', checked = True)
  File "gui_integration_tests/test_cases.py", line 143, in
_click_interestcategory
    id = self.interestcategories[name].key().id()
KeyError: '1'

????????????????????????????????????????????????????????????????????????????????

################################################################################
ERROR: test_event_list_upcoming_anyone
(gui_integration_tests.tests.privacy_settings.TestPrivacySettings__anyone)
????????????????????????????????????????????????????????????????????????????????

Traceback (most recent call last):
  File "gui_integration_tests/tests/privacy_settings.py", line 102, in
test_event_list_upcoming_anyone
    future = True)
  File "gui_integration_tests/tests/privacy_settings.py", line 27, in
_see_only_attendees_user_has_permission_for
    future = future)
  File "gui_integration_tests/tests/privacy_settings.py", line 38, in
__test_attendees
    sel.open('/events/%i'%self.test_object_index[event].key().id())
  File
"/Library/Python/2.5/site-packages/selenium-1.0_SNAPSHOT-py2.5.egg/selenium.py",
line 764, in open
    self.do_command("open", [url,])
  File
"/Library/Python/2.5/site-packages/selenium-1.0_SNAPSHOT-py2.5.egg/selenium.py",
line 215, in do_command
    raise Exception, data
Exception: Timed out after 30000ms

????????????????????????????????????????????????????????????????????????????????

################################################################################
ERROR: test_new
(gui_integration_tests.tests.update_profile.UpdateProfileTest)
????????????????????????????????????????????????????????????????????????????????

Traceback (most recent call last):
  File "gui_integration_tests/tests/update_profile.py", line 18, in test_new
    sel.wait_for_page_to_load("30000")
  File
"/Library/Python/2.5/site-packages/selenium-1.0_SNAPSHOT-py2.5.egg/selenium.py",
line 1696, in wait_for_page_to_load
    self.do_command("waitForPageToLoad", [timeout,])
  File
"/Library/Python/2.5/site-packages/selenium-1.0_SNAPSHOT-py2.5.egg/selenium.py",
line 215, in do_command
    raise Exception, data
Exception: Timed out after 30000ms

????????????????????????????????????????????????????????????????????????????????

################################################################################
FAIL: test_nav_menu
(gui_integration_tests.tests.navigation_tabs.TestOrganizationNavigation)
????????????????????????????????????????????????????????????????????????????????

Traceback (most recent call last):
  File "gui_integration_tests/tests/navigation_tabs.py", line 34, in
test_nav_menu
    self.failUnless(sel.is_text_present("Temporary Help Information"))
AssertionError

????????????????????????????????????????????????????????????????????????????????

################################################################################
FAIL: test_nav_menu
(gui_integration_tests.tests.navigation_tabs.TestVolunteerNavigation)
????????????????????????????????????????????????????????????????????????????????

Traceback (most recent call last):
  File "gui_integration_tests/tests/navigation_tabs.py", line 64, in
test_nav_menu
    self.failUnless(sel.is_text_present("Temporary Help Information"))
AssertionError

????????????????????????????????????????????????????????????????????????????????

################################################################################
FAIL: test_event_list_past_attender
(gui_integration_tests.tests.privacy_settings.TestPrivacySettings)
????????????????????????????????????????????????????????????????????????????????

Traceback (most recent call last):
  File "gui_integration_tests/tests/privacy_settings.py", line 81, in
test_event_list_past_attender
    self._see_all_attendees()
  File "gui_integration_tests/tests/privacy_settings.py", line 20, in
_see_all_attendees
    future = future)
  File "gui_integration_tests/tests/privacy_settings.py", line 46, in
__test_attendees

self.failUnless(sel.is_element_present("//a[@id='volunteer_link[%i]']"%self.test
_object_index[volunteer].key().id()))
AssertionError

????????????????????????????????????????????????????????????????????????????????

################################################################################
FAIL: test_event_creator_upcoming
(gui_integration_tests.tests.privacy_settings.TestPrivacySettings_EventCreator)
????????????????????????????????????????????????????????????????????????????????

Traceback (most recent call last):
  File "gui_integration_tests/tests/privacy_settings.py", line 127, in
test_event_creator_upcoming
    self._see_all_attendees(future = True)
  File "gui_integration_tests/tests/privacy_settings.py", line 20, in
_see_all_attendees
    future = future)
  File "gui_integration_tests/tests/privacy_settings.py", line 46, in
__test_attendees

self.failUnless(sel.is_element_present("//a[@id='volunteer_link[%i]']"%self.test
_object_index[volunteer].key().id()))
AssertionError

????????????????????????????????????????????????????????????????????????????????

################################################################################

                        'gui_integration_tests' package
                              28 tests (1611.190s)

                                    ERRORS!
                             (failures=4, errors=3)

################################################################################

```

Original comment by `acwa...@gmail.com` on 13 Jul 2009 at 7:00

**Comment by GoogleCodeExporter** [comment]
```
Below are the details for my changes. 
I think the timeouts are not real problems. Selenium just seems to behave 
strangely.
I've ran all of the privacy_settings and in the end it ran without errors, but 
also
without OK. Is this a selenium quirk. 


(gui_integration_tests.tests.edit_event.TestEditEvent__Owner)
    fixed
(gui_integration_tests.tests.update_profile.UpdateProfileTest)
    seems ok, was Exception: Timed out after 30000ms 
(gui_integration_tests.tests.navigation_tabs.TestOrganizationNavigation)
    fixed, was looking for text that had changed
(gui_integration_tests.tests.navigation_tabs.TestVolunteerNavigation)
    fixed, was looking for text that had changed


(gui_integration_tests.tests.privacy_settings.TestPrivacySettings__anyone)
(gui_integration_tests.tests.privacy_settings.TestPrivacySettings)
(gui_integration_tests.tests.privacy_settings.TestPrivacySettings_EventCreator)
    fixed all privacy settings, take into account pagination, but there were also some
intermittent timeouts


```

Original comment by `acwa...@gmail.com` on 13 Jul 2009 at 11:33
- Changed state: **Fixed**
